/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.lagagain.tornadoFX.calculator

import javafx.scene.layout.GridPane
import tornadofx.*



class myView : View() {
    override val root : GridPane by fxml("/views/Calculator.fxml")
}

class MyApp: App() {
    override val primaryView = myView::class
}

// class App {
//     val greeting: String
//         get() {
//             return "Hello world."
//         }
// }

fun main(args: Array<String>) {
    launch<MyApp>(args)
}
 
